-- Add missing columns to customers table
ALTER TABLE customers ADD COLUMN IF NOT EXISTS type TEXT DEFAULT 'business';
ALTER TABLE customers ADD COLUMN IF NOT EXISTS salutation TEXT;
ALTER TABLE customers ADD COLUMN IF NOT EXISTS first_name TEXT;
ALTER TABLE customers ADD COLUMN IF NOT EXISTS last_name TEXT;
ALTER TABLE customers ADD COLUMN IF NOT EXISTS company_name TEXT;
ALTER TABLE customers ADD COLUMN IF NOT EXISTS display_name TEXT;
ALTER TABLE customers ADD COLUMN IF NOT EXISTS work_phone TEXT;
ALTER TABLE customers ADD COLUMN IF NOT EXISTS mobile TEXT;
ALTER TABLE customers ADD COLUMN IF NOT EXISTS currency TEXT DEFAULT 'AED';
ALTER TABLE customers ADD COLUMN IF NOT EXISTS language TEXT DEFAULT 'en';
ALTER TABLE customers ADD COLUMN IF NOT EXISTS billing_address TEXT;
ALTER TABLE customers ADD COLUMN IF NOT EXISTS shipping_address TEXT;
ALTER TABLE customers ADD COLUMN IF NOT EXISTS remarks TEXT;
ALTER TABLE customers ADD COLUMN IF NOT EXISTS entity_type TEXT;
ALTER TABLE customers ADD COLUMN IF NOT EXISTS entity_sub_type TEXT;
ALTER TABLE customers ADD COLUMN IF NOT EXISTS incorporation_date DATE;
ALTER TABLE customers ADD COLUMN IF NOT EXISTS trade_license_authority TEXT;
ALTER TABLE customers ADD COLUMN IF NOT EXISTS trade_license_number TEXT;
ALTER TABLE customers ADD COLUMN IF NOT EXISTS trade_license_issue_date DATE;
ALTER TABLE customers ADD COLUMN IF NOT EXISTS trade_license_expiry_date DATE;
ALTER TABLE customers ADD COLUMN IF NOT EXISTS business_activity TEXT;
ALTER TABLE customers ADD COLUMN IF NOT EXISTS is_freezone BOOLEAN DEFAULT FALSE;
ALTER TABLE customers ADD COLUMN IF NOT EXISTS freezone_name TEXT;
ALTER TABLE customers ADD COLUMN IF NOT EXISTS shareholders JSONB DEFAULT '[]'::jsonb;
ALTER TABLE customers ADD COLUMN IF NOT EXISTS authorised_signatories TEXT;
ALTER TABLE customers ADD COLUMN IF NOT EXISTS share_capital TEXT;
ALTER TABLE customers ADD COLUMN IF NOT EXISTS tax_treatment TEXT;
ALTER TABLE customers ADD COLUMN IF NOT EXISTS trn TEXT;
ALTER TABLE customers ADD COLUMN IF NOT EXISTS vat_registered_date DATE;
ALTER TABLE customers ADD COLUMN IF NOT EXISTS first_vat_filing_period TEXT;
ALTER TABLE customers ADD COLUMN IF NOT EXISTS vat_filing_due_date DATE;
ALTER TABLE customers ADD COLUMN IF NOT EXISTS vat_reporting_period TEXT;
ALTER TABLE customers ADD COLUMN IF NOT EXISTS corporate_tax_treatment TEXT;
ALTER TABLE customers ADD COLUMN IF NOT EXISTS corporate_tax_trn TEXT;
ALTER TABLE customers ADD COLUMN IF NOT EXISTS corporate_tax_registered_date DATE;
ALTER TABLE customers ADD COLUMN IF NOT EXISTS corporate_tax_period TEXT;
ALTER TABLE customers ADD COLUMN IF NOT EXISTS first_corporate_tax_period_start DATE;
ALTER TABLE customers ADD COLUMN IF NOT EXISTS first_corporate_tax_period_end DATE;
ALTER TABLE customers ADD COLUMN IF NOT EXISTS corporate_tax_filing_due_date DATE;
ALTER TABLE customers ADD COLUMN IF NOT EXISTS business_registration_number TEXT;
ALTER TABLE customers ADD COLUMN IF NOT EXISTS place_of_supply TEXT;
ALTER TABLE customers ADD COLUMN IF NOT EXISTS opening_balance NUMERIC DEFAULT 0;
ALTER TABLE customers ADD COLUMN IF NOT EXISTS payment_terms TEXT;
ALTER TABLE customers ADD COLUMN IF NOT EXISTS portal_access BOOLEAN DEFAULT FALSE;
ALTER TABLE customers ADD COLUMN IF NOT EXISTS contact_persons JSONB DEFAULT '[]'::jsonb;
ALTER TABLE customers ADD COLUMN IF NOT EXISTS custom_data JSONB DEFAULT '{}'::jsonb;
